### ISSUE TITLE
Move community server from discord to matrix.org

### ISSUE THREAD

**Issue by paniash** [unitaryfund/community-roadmap#8]
- [X] I have searched the [issues](https://github.com/unitaryfund/community-roadmap/issues) of this repository and believe that this is not a duplicate.

## Summary 🧾

I think it would be in the spirit of opensource and free (as in freedom) software if the community server is moved from discord to matrix.org. Discord has been a proprietary software which has various restrictions in its TOS (such as complete ban of user if a third-party client is used) and matrix being an open and free standard would be a very good and viable choice.

Various opensource projects have had official community servers on matrix (such as librecube, mlpack, NixOS, Rust, etc.) and I think it would be a great idea if unitary-fund followed the same.

## Motivation 🔦

To promote open and free standards of communication protocols such as matrix.

**Comment by paniash** [comment]
Any opinion on this? @crazy4pi314

**Comment by crazy4pi314** [comment]
Hi @paniash! Sorry I didn't see this, I think I was missing some notifications while still closing out unitaryHACK :)

I like matrix too (open source tools are great)! The reason we didn't go with this in the first place is that there was a lot of overhead in managing our own server (or cost to paying for external hosting) and that when building community it is important to meet people where they are. I don't like Discord being proprietary, but the history of the company decisions is relatively good and they are really quick in responding to community feedback (ex. they saw folks using bots to manage codes of conduct and then just built that in as a feature). 

By the logic above, Slack would also be a popular choice as many folks already use that for work, but my challenges were how to setup a code of conduct gate, a lack of voice/video channels (that may be different now), and some of the features we would like were paid. The last is not the biggest issue, but again my goal was trying to make the platform and asks of our users as small as possible to make it easy for everyone to participate, while still having the moderation tools we need to keep it safe. It's much harder to get someone to engage regularly or even sign up in the first place if they are not already using the tools you are using to build the community. I think this is something we could consider (possibly with bridges to other platforms) in the future, but for right now I think the best tool for us is Discord.
